/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import javax.swing.JOptionPane;

/**
 *
 * @author luas_lp
 */
public class frmOperaciones extends javax.swing.JFrame {

    /**
     * Creates new form frmOperaciones
     */
    public frmOperaciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblResta.setVisible(false);
        lblSuma.setVisible(false);
        btnCargar.setEnabled(false);
    }

    //declaramos variables globales para el manejo de cadenas 
    String cadenaA1, aux,cadenaB1, aux2, simbolo;
    int est=0, op, longitud1, longitud2, longtotal, apuntador=0;
    String arreglo1[];
    int arreglo2[];
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCadena1 = new javax.swing.JTextField();
        txtCadena2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblCadena2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLeer = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblCadena1 = new javax.swing.JLabel();
        lblSimbolo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblResta = new javax.swing.JLabel();
        lblSuma = new javax.swing.JLabel();
        lblOperacion = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbOp = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setText("L={w/w suma o resta dos cadenas unitarias}");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, 30));
        jPanel1.add(txtCadena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 267, 30));
        jPanel1.add(txtCadena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 267, 30));

        jLabel1.setText("Simbolo de operacion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));
        jPanel1.add(lblCadena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 30, 20));

        jLabel3.setText("Segunda Cadena");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        btnLeer.setText("1) LEER CADENAS");
        btnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerActionPerformed(evt);
            }
        });
        jPanel1.add(btnLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 170, 50));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        jLabel9.setText("MAQUINA DE TURING");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        btnCargar.setText("2) CARGAR CADENAS");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 170, 50));

        jLabel4.setText("Primera Cadena");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));
        jPanel1.add(lblCadena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 30, 20));
        jPanel1.add(lblSimbolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 30, 20));

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 770, 100, 50));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 770, 100, 50));

        lblResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/resta.png"))); // NOI18N
        lblResta.setIconTextGap(2);
        jPanel1.add(lblResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 540, 350));

        lblSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/suma.png"))); // NOI18N
        lblSuma.setIconTextGap(2);
        jPanel1.add(lblSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 280, 250));

        lblOperacion.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        lblOperacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 450, 30));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("#");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 30, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("#");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 30, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("#");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 30, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("#");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 30, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("#");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 30, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("#");
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 30, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("#");
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 30, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("#");
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 30, -1));

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("#");
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 30, -1));

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("#");
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 30, -1));

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("#");
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 30, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("#");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 60, 40));

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("-");
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 30, -1));

        jTextField16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setText("-");
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 30, -1));

        jTextField18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setText("-");
        jPanel1.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 30, -1));

        jTextField21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setText("-");
        jPanel1.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 30, -1));

        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("-");
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 30, -1));

        jTextField15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setText("-");
        jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 30, -1));

        jTextField20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.setText("-");
        jPanel1.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 30, -1));

        jTextField22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setText("-");
        jPanel1.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 30, -1));

        jTextField14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("-");
        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 30, -1));

        jTextField17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setText("-");
        jPanel1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 30, -1));

        jTextField19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setText("-");
        jPanel1.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 30, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Caracteres");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Estado:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 40));

        cmbOp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));
        jPanel1.add(cmbOp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerActionPerformed

        //se guarda el simbolo
        op = cmbOp.getSelectedIndex();
        if(op == 0)
        {
            lblSuma.setVisible(true);
            lblResta.setVisible(false);
            simbolo = "+";
        }else if(op == 1)
        {
            lblResta.setVisible(true);
            lblSuma.setVisible(false);
            simbolo = "-";
        }
        //validaciones para el ingreso de las cadenas
        if(txtCadena1.getText().equals("")||txtCadena1.getText().equals(null))
        {
            JOptionPane.showMessageDialog(rootPane,"Debe ingresar algun dato en la cadena 1");
            txtCadena1.grabFocus();
            
        }
        else if (txtCadena2.getText().equals("")||txtCadena2.getText().equals(null))
        {
            JOptionPane.showMessageDialog(rootPane,"Debe ingresar algun dato en la cadena 2");
            txtCadena2.grabFocus();
        }else if(!validarCadena(txtCadena1.getText().trim())) //validacion de cadena binaria 1
        {
          JOptionPane.showMessageDialog(rootPane,"Debe ingresar valores unitarios unicamente en la cadena 1");
          txtCadena1.grabFocus();
        }else if(!validarCadena(txtCadena2.getText().trim())) //validacion de cadena binaria 2
        {
          JOptionPane.showMessageDialog(rootPane,"Debe ingresar valores unitarios unicamente en la cadena 2");
          txtCadena2.grabFocus();
        }
        else 
        {
            //se guarda la cadena ingresada en el primer txt
            cadenaA1=txtCadena1.getText();
            //se encuentra la longitud de la cadena 1
            longitud1 = cadenaA1.length();
            //se guarda la cadena 2
            cadenaB1 = txtCadena2.getText()+"#";
            //se encuentra la longitud de la cadena 2
            longitud2 = cadenaB1.length();

            
            //longitud del arreglo
            longtotal = longitud1 + longitud2 + 1;
            arreglo1= new String [longtotal+1];
            // condicion para el maximo de caracteres
            if(longtotal > 11)
            {
                JOptionPane.showMessageDialog(rootPane, "Las cadenas exceden el limite de caracteres, por el momento solo se permiten 11 caracteres en total");
            }else
            {
                //se llena el arreglo con la primera cadena
                for(int i =0; i<longitud1; i++)
                {
                    arreglo1[i]=""+cadenaA1.charAt(i);
                }   
                
                //se agrega el simbolo al arreglo
                arreglo1[longitud1]= ""+simbolo;
               
                //se agrega la segunda cadena al arreglo
                for(int j =0 + 1; j<=longitud2; j++)
                {
                    arreglo1[longitud1 + j]= ""+cadenaB1.charAt(j-1);
                }   
                iniciocajas1();
            }
        }
        lblOperacion.setText("Comparando Cadenas, caracter por caracter...");
        btnCargar.setEnabled(true);
    }//GEN-LAST:event_btnLeerActionPerformed

        //funcion para validar las cadenas binarias
    public static boolean validarCadena(String datos)
    {
        return datos.matches("[1]*");
    }
    
        //funciones
    void iniciocajas1(){
        int pos=0;
        while (pos<longtotal){
            switch (pos){
                case 0:{
                    jTextField1.setText(arreglo1[0]);
                    break;}
                case 1:{
                    jTextField2.setText(arreglo1[1]);
                    break;}
                case 2:{
                    jTextField3.setText(arreglo1[2]);
                    break;}
                case 3:{
                    jTextField4.setText(arreglo1[3]);
                    break;}
                case 4:{
                    jTextField5.setText(arreglo1[4]);
                    break;}
                case 5:{
                    jTextField6.setText(arreglo1[5]);
                    break;}
                case 6:{
                    jTextField7.setText(arreglo1[6]);
                    break;}
                case 7:{
                    jTextField8.setText(arreglo1[7]);
                    break;}
                case 8:{
                    jTextField9.setText(arreglo1[8]);
                    break;}
                case 9:{
                    jTextField10.setText(arreglo1[9]);
                    break;}
                case 10:{
                    jTextField11.setText(arreglo1[10]);
                    break;}
            }
            pos++;
        }
           jTextField12.setText("^");
    }
    
    
    void llenarcabezal(){
        jTextField12.setText("-");
        jTextField13.setText("-");
        jTextField14.setText("-");
        jTextField15.setText("-");
        jTextField16.setText("-");
        jTextField17.setText("-");
        jTextField18.setText("-");
        jTextField19.setText("-");
        jTextField20.setText("-");
        jTextField21.setText("-");
        jTextField22.setText("-");
    }
    
    void cabezal(){
        switch(apuntador){
            case 0:{
                jTextField12.setText("^");
                break;
            }
             case 1:{
                jTextField13.setText("^");
                break;
             }
             case 2:{
                jTextField14.setText("^");
                break;
             }
             case 3:{
                jTextField15.setText("^");
                break;
             }
             case 4:{
                jTextField16.setText("^");
                break;
             }
             case 5:{
                jTextField17.setText("^");
                break;
             }
             case 6:{
                jTextField18.setText("^");
                break;
             }
             case 7:{
                jTextField19.setText("^");
                break;
             }
             case 8:{
                jTextField20.setText("^");
                break;
             }
             case 9:{
                jTextField21.setText("^");
                break;
             }
             case 10:{
                jTextField22.setText("^");
                break;
             }
        }
        jLabel6.setText("q"+est);
    }
    
    
    void movder(){
        apuntador++;   
    }
    
    void movizq(){
        apuntador= apuntador - 1;
    }
    
    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
     
        if(op == 1)
        {
            llenarcabezal();
            switch(est){
                case 0:{
                    q0();
                    break;
                }
                case 1:{
                    q1();
                    break;
                }
                case 2:{
                    q2();
                    break;
                }
                case 3:{
                    q3();
                    break;
                }
                case 4:{
                    q4();
                    break;
                }
                case 5:{
                    q5();
                    break;
                }
                case 6:{
                    q6();
                    break;
                }
                case 7:{
                    q7();
                    break;
                }
                case 8:{
                    q8();
                    break;
                }
                case 9:{
                    q9();
                    break;
                }
            }
        }//si es suma
        if(op == 0)
        {
            llenarcabezal();
            switch(est){
                case 0:{
                    qr0();
                    break;
                }
                case 1:{
                    qr1();
                    break;
                }
                case 2:{
                    qr2();
                    break;
                }
                case 3:{
                    qr3();
                    break;
                }
                case 4:{
                    qr4();
                    break;
                }
               
            }
        }
        
    }//GEN-LAST:event_btnCargarActionPerformed
  void actcadena(String dat){
        switch(apuntador){
            case 0: {
                jTextField1.setText(dat);
                break;
            }
            
            case 1:{
                jTextField2.setText(dat);
                break;
            }
            case 2:{
                jTextField3.setText(dat);
                break;
            }
            case 3:{
                jTextField4.setText(dat);
                break;
            }
            case 4:{
                jTextField5.setText(dat);
                break;
            }
            case 5:{
                jTextField6.setText(dat);
                break;
            }
            case 6:{
                jTextField7.setText(dat);
                break;
            }
            case 7:{
                jTextField8.setText(dat);
                break;
            }
            case 8:{
                jTextField9.setText(dat);
                break;
            }
            case 9:{
                jTextField10.setText(dat);
                break;
            }
            case 10:{
                jTextField11.setText(dat);
                break;
            }           
            case 11:{
                jTextField12.setText(dat);
                break;
            }
        }
    }
  
    //estados para la resta
    void q0()
    {
     cabezal();
     aux = arreglo1[apuntador];     
     if(aux.equals("1")) 
     {
         est = 1;
         arreglo1[apuntador]="1";
         actcadena("1");
         movder();
     }

    }
    
    void q1()
    {
     cabezal();
     aux = arreglo1[apuntador];
     if(aux.equals("1")) 
     {
         est = 1;
         arreglo1[apuntador]="1";
         actcadena("1");
         movder();
     }
     
     if(aux.equals("-")) 
     {
         est = 2;
         arreglo1[apuntador]="-"; 
         actcadena("-");
         movder();
      }
    }
    
    void q2()
    {
     cabezal();
     aux = arreglo1[apuntador];
     if(aux.equals("1")) 
     {
         est = 2;
         arreglo1[apuntador]="1";
         actcadena("1");
         movder();
     }
     
     if(aux.equals("#")) 
     {
         est = 3;
         arreglo1[apuntador]="Z";
         actcadena("Z");
         movizq();
     }

    }
    
    void q3()
    {
     cabezal();
     aux = arreglo1[apuntador];
     if(aux.equals("1")) 
     {
         est = 3;
         arreglo1[apuntador]="1";
         actcadena("1");
         movizq();
         
     }
     
     if(aux.equals("-")) 
     {
         est = 4;
         arreglo1[apuntador]="-";
         actcadena("-");
         movder();
     }
    }
    
    
    void q4()
    {
     cabezal();
     aux = arreglo1[apuntador];
     if(aux.equals("#")) 
     {
         est = 4;
         arreglo1[apuntador]="#";
         actcadena("#");
         movder();
     }
     
     if(aux.equals("1")) 
     {
         est = 5;
         arreglo1[apuntador]="#";
         actcadena("#");
         movizq();
     }
     
     if(aux.equals("Z")) 
     {
         est = 8;
         arreglo1[apuntador]="#";
         actcadena("#");
         movizq();
     }
    }
    
    
    void q5()
    {
     cabezal();
     aux = arreglo1[apuntador];
     if(aux.equals("#")) 
     {
         est = 5;
         arreglo1[apuntador]="#";
         actcadena("#");
         movizq();
     }

     if(aux.equals("-")) 
     {
         est = 6;
         arreglo1[apuntador]="-";
         actcadena("-");
         movizq();
     }
     
    }
    
    void q6()
    {
     cabezal();
     aux = arreglo1[apuntador];
     if(aux.equals("#")) 
     {
         est = 6;
         arreglo1[apuntador]="#";
         actcadena("#");
         movizq();
     }
     
     if(aux.equals("1")) 
     {
         est = 7;
         arreglo1[apuntador]="#";
         actcadena("#");
         movder();
     }

    }
    
    void q7()
    {
     cabezal();
     aux = arreglo1[apuntador];
     if(aux.equals("#")) 
     {
         est = 7;
         arreglo1[apuntador]="#";
         actcadena("#");
         movder();
     }
     
     if(aux.equals("-")) 
     {
         est = 4;
         arreglo1[apuntador]="-";
         actcadena("-");
         movder();
     }
    }
    
    void q8()
    {
     cabezal();
     aux = arreglo1[apuntador];
     if(aux.equals("#")) 
     {
         est = 8;
         arreglo1[apuntador]="#";
         actcadena("#");
         movizq();
     }
     
     if(aux.equals("-")) 
     {
         est = 9;
         arreglo1[apuntador]="#";
         actcadena("#");
         movizq();
         
     }
     
    }
    
    
    void q9()
    {
        cabezal();
        JOptionPane.showMessageDialog(this,"La cadena ha sido aceptada, resta realizada");
        
    }
    
    //estados para la resta
    void qr0()
    {
     cabezal();
     aux = arreglo1[apuntador];     
     if(aux.equals("1")) 
     {
         est = 1;
         arreglo1[apuntador]="1";
         actcadena("1");
         movder();
     }

    }
    
    void qr1()
    {
     cabezal();
     aux = arreglo1[apuntador];
     if(aux.equals("1")) 
     {
         est = 1;
         arreglo1[apuntador]="1";
         actcadena("1");
         movder();
     }
     
     if(aux.equals("+")) 
     {
         est = 2;
         arreglo1[apuntador]="1"; 
         actcadena("1");
         movder();
      }
    }
    
    void qr2()
    {
     cabezal();
     aux = arreglo1[apuntador];
     if(aux.equals("1")) 
     {
         est = 2;
         arreglo1[apuntador]="1";
         actcadena("1");
         movder();
     }
     
     if(aux.equals("#")) 
     {
         est = 3;
         arreglo1[apuntador]="#";
         actcadena("#");
         movizq();
     }

    }
    
    void qr3()
    {
     cabezal();
     aux = arreglo1[apuntador];
     if(aux.equals("1")) 
     {
         est = 4;
         arreglo1[apuntador]="#";
         actcadena("#");
         //movder();    
     }
     
    }
    
    
    void qr4()
    {
        cabezal();
        JOptionPane.showMessageDialog(this,"La cadena ha sido aceptada, suma realizada");
    }
    
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        frmInicio fi = new frmInicio();
        fi.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOperaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnLeer;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbOp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblCadena1;
    private javax.swing.JLabel lblCadena2;
    private javax.swing.JLabel lblOperacion;
    private javax.swing.JLabel lblResta;
    private javax.swing.JLabel lblSimbolo;
    private javax.swing.JLabel lblSuma;
    private javax.swing.JTextField txtCadena1;
    private javax.swing.JTextField txtCadena2;
    // End of variables declaration//GEN-END:variables
}
